[build]
  command = "yarn build"
  publish =  "dist"
[[headers]]
  for = "*.woff"
  [headers.values]
    content-type = "font/woff"
    cache-control = "public, max-age=31536000"
[[headers]]
  for = "*.woff2"
  [headers.values]
    content-type = "font/woff2"
    cache-control = "public, max-age=31536000"
[context.production]
  environment = { NODE_VERSION = "14.15.3" }
